version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - my_network

  nestjs-app:
    build: .
    container_name: nestjs_app
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE: ${DATABASE}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    networks:
      - my_network
    volumes:
      - .:/app
    command: npm run start:prod

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
